# Generated by Django 4.2.27 on 2026-01-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(default='e', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='choice_1',
            field=models.TextField(default='a', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='choice_2',
            field=models.TextField(default='b', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='choice_3',
            field=models.TextField(default='c', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='choice_4',
            field=models.TextField(default='d', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.TextField(default='question', max_length=60),
            preserve_default=False,
        ),
    ]
