# Generated by Django 4.2.27 on 2026-01-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_alter_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='name',
            field=models.TextField(default='First Quiz', max_length=60),
            preserve_default=False,
        ),
    ]
