# Generated by Django 4.2.27 on 2026-01-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_quiz_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.JSONField(default='egg'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_1',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_2',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_3',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_4',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=60),
        ),
    ]
