# Generated by Django 4.2.27 on 2026-01-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0006_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice',
            field=models.CharField(default='a'),
            preserve_default=False,
        ),
    ]
