# Generated by Django 4.2.27 on 2026-01-06 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0007_choice_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choice_1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_4',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
