# Generated by Django 4.2.27 on 2026-01-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0008_remove_question_choice_1_remove_question_choice_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.JSONField(default={'key': 'value'}),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='Question text', max_length=60),
        ),
    ]
