# Generated by Django 4.2.27 on 2026-01-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0009_alter_question_answer_alter_question_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.JSONField(),
        ),
    ]
