# Generated by Django 4.2.27 on 2026-01-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0011_alter_quiz_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='Question text', max_length=100),
        ),
    ]
